version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # Maintain dependencies for Git Submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # dependabot seems willing to look 1 level deep
  - package-ecosystem: "pip"
    directory: "/GUI"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/PCC"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/VMC/apriltag/python"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/VMC/fcm"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/VMC/fusion"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/VMC/pcm"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/VMC/sandbox"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/VMC/status"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/VMC/thermal"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/VMC/vio"
    schedule:
      interval: "weekly"
    target-branch: "develop"