[tool.autoflake]
recursive = true
in-place = true

[tool.isort]
profile = "black"

[tool.flake8]
# E501 is line too long
# E203 is whitespace before ':'
# W503 is line break before binary operator
ignore = "E501, E203, W503"

[tool.black]
line-length = 200
extend-exclude = '''
/(
scripts
  | VMC/apriltag
  | VMC/fusion
  | VMC/mavp2p
  | VMC/mqtt
  | VMC/scripts
  | VMC/simulator
  | VMC/status
  | VMC/thermal
  | VMC/vio
  | PCC
  | PX4
)
'''
