[tool.isort]
profile = "black"
multi_line_output = 3
skip_glob = [
  "VMC/apriltag/c/libraries/*",
  "PCC/libraries/Queue/*",
] # Exclude submodules

[tool.black]
line-length = 200
# Exclude submodules
extend-exclude = '''
/(
VMC/apriltag/c/libraries
  | PCC/libraries/Queue/
)
'''

[tool.autoflake]
recursive = true
in-place = true
remove-all-unused-imports = true
expand-star-imports = true
remove-duplicate-keys = true
remove-unused-variables = true
exclude = [
  "cpplint.py",
  "mqttsas.py",
  "MQTTV5.py",
] # Ignore a couple problematic files in submodules

[tool.flake8] # flake8 is kinda niche, just reports problems, doesn't fix them. Also yaps a lot about errors that aren't real/don't matter
# E501 is line too long
# E203 is whitespace before ':'
# W503 is line break before binary operator
ignore = ["E501, E203, W503"]
