name: Build Container Fusion

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
      - dev
      - dependabot
    paths:
      - "VMC/fusion/**"
  push:
    branches:
      - main
    paths:
      - "VMC/fusion/**"

jobs:
  fusion:
    uses: ./.github/workflows/container.yml
    with:
      image: "fusion"