name: Build GUI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
      - dev
      - dependabot
    paths:
      - "GUI/**"
  push:
    branches:
      - main
    paths:
      - "GUI/**"

jobs:
  gui-build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: GUI

      - name: Install Packages
        run: python scripts/install_requirements.py --directory GUI --strict
      
      - name: Run app.py
        run: python GUI/app.py
